name: terraform-apply

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  AWS_REGION: "us-east-1"

jobs:
  apply:
    # Garante que é PR e tolera espaços/maiúsculas no comentário
    if: >
      github.event.issue.pull_request != '' &&
      contains(toJson(github.event.comment.body), '/atlantis apply')
    runs-on: ubuntu-latest

    steps:
      - name: Debug do evento
        run: |
          echo "actor=${{ github.actor }}"
          echo "body<<EOF"
          echo "${{ github.event.comment.body }}"
          echo "EOF"

      # (Opcional) Permitir apenas a dona do repo
      - name: Apenas a @michelleamesquita pode aplicar
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const actor = context.actor;
            const allowed = ["michelleamesquita"];
            if (!allowed.includes(actor)) {
              core.setFailed(`Usuário @${actor} não autorizado a aplicar.`);
            }

      # Aprovação opcional (sempre seta approved)
      - name: Check PR approval (opcional)
        id: guard
        uses: actions/github-script@v7
        with:
          script: |
            const requireApproval = false; // mude para true se quiser exigir
            if (!requireApproval) { core.setOutput('approved','true'); return; }
            const { owner, repo } = context.repo;  // pega owner/repo corretos
            const prNumber = context.payload.issue.number;
            const reviews = await github.rest.pulls.listReviews({ owner, repo, pull_number: prNumber });
            const approved = reviews.data.some(r => r.state === 'APPROVED');
            core.setOutput('approved', approved ? 'true' : 'false');

      - name: Fail if not approved
        if: steps.guard.outputs.approved == 'false'
        run: |
          echo "PR não aprovado ainda."
          exit 1

      # Tenta checar o PR HEAD (branch do autor)
      - name: Checkout PR HEAD
        id: co_head
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      # Se o HEAD não existir, tenta o merge ref
      - name: Checkout PR MERGE ref (fallback)
        if: steps.co_head.outcome != 'success'
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Apply
        id: apply
        working-directory: terraform
        run: |
          set -euo pipefail
          terraform apply -auto-approve -no-color \
            -var="suffix=pr-${{ github.event.issue.number }}" 2>&1 | tee apply.txt
          echo "APPLY<<EOF" >> $GITHUB_OUTPUT
          sed -E 's/\x1b\[[0-9;]*m//g' apply.txt | tail -n 200 >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment Apply Result
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-apply
          number: ${{ github.event.issue.number }}
          message: |
            **Resultado do Apply (PR #${{ github.event.issue.number }})**
            ```
            ${{ steps.apply.outputs.APPLY }}
            ```
