name: terraform-plan

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  AWS_REGION: "us-east-1"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Plan
        id: plan
        working-directory: terraform
        run: |
          terraform plan -no-color \
            -var="suffix=pr-${{ github.event.number }}" \
            -out=tfplan 2>&1 | tee plan.txt
          echo "PLAN<<EOF" >> $GITHUB_OUTPUT
          sed -E 's/\x1b\[[0-9;]*m//g' plan.txt | tail -n 200 >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-plan
          message: |
            **Terraform Plan (PR #${{ github.event.number }})**
            ```
            ${{ steps.plan.outputs.PLAN }}
            ```
            _Para aplicar, comente:_ `/atlantis apply`
